### ISSUE TITLE
jMonitor cannot pass arguments to the monitored process

### ISSUE THREAD

**Issue by graeme-a-stewart** [key4hep/key4hep-validation#1]
- OS version: e.g. CS8
 - Compiler version: Python 2.7.18 / Python 3.6.8
 - Package version: head of main
 - Reproduced by: 

```
./jMonitor sleep 10
usage: jMonitor [-h] [-T MAXTIME] [-WT WALLTIME] [-M MAXVIR] [--enable-parser]
                [-p FATALPATTERN] [--enable-monitor] [-i INTERVAL]
                [-b {root,matplotlib}] [--enable-plotref] [-f PLOTREFFILE]
                [-o PLOTREFOUTPUT] [-m {Kolmogorov,Chi2}] [-c HISTTESTCUT]
                [--gen-log] [-n NAME]
                command
jMonitor: error: unrecognized arguments: 10
``` 

 - Goal: It should be possible to pass an arbitrary number of arguments to the executed program that jMonitor wraps

The very standard way to do this is to separate the arguments to jMonitor from the arguments to the target program with a `--`. So this is the syntax that I would expect to have work:

```
./jMonitor -- sleep 10
```

```
./jMonitor -- k4run runCaloSim.py  --filename fccee_idea_LAr_pgun.root  --GenAlg.MomentumRangeParticleGun.MomentumMax 5000 --GenAlg.MomentumRangeParticleGun.MomentumMin 5000  -n 500 
```

The `--` is directly supported by `argparse`; the `command` option would need to become multi-valued (i.e., `nargs='+'`).

**Comment by graeme-a-stewart** [comment]
BTW, I have a fix for this, so I can submit it as a PR if desired

**Comment by feipengsy** [comment]
Thank you Graeme. Please go ahead.
