### ISSUE TITLE
Default Python for jMonitor is deprecated

### ISSUE THREAD

**Issue by graeme-a-stewart** [key4hep/key4hep-validation#3]
The shebang execution of `jMonitor` uses `python2`, which has been deprecated for more than 2 years!

As far as I can see everything works fine with `python3`, so can this be updated please?

Thanks

**Comment by feipengsy** [comment]
@graeme-a-stewart Thanks for spotting this. This was due to some tests on a project that still uses python2.
I've made the change in commit ad8609f to fix this.

**Comment by graeme-a-stewart** [comment]
Thanks! So we can close this one now.
